# Project information
site_name: NYUSH HPC Docs
site_description: Public documentation of the NYUSH HPC infrastructure.
site_author: NYUSH HPC
site_url: https://github.com/hgc123123/nyush-cluster.git

# Repository
repo_name: NYUSH HPC Docs
repo_url: https://github.com/hgc123123/nyush-cluster.git
edit_uri: 'edit/main/nyush-cluster/docs/'

# Copyright
copyright: 2024, NYUSH HPC

# Theming, Configuration
theme:
  name: material
  # Custom overrides
  custom_dir: overrides
  palette:
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
    - content.action.edit
strict: true
extra_css:
  - css/extra.css

# Plugins
plugins:
  - search
  - git-revision-date-localized

# Extensions
markdown_extensions:
  - attr_list
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.superfences

# Page tree
nav:
  - index.md
  - "Administrative":
    - "Getting Access": admin/getting-access.md
    - "Maintenance etc.": admin/maintenance.md
    - "Policies": admin/policies.md
  - "Connecting":
    - "Overview": "connecting/connecting.md"
    - "From External": connecting/from-external.md
    - "Connection Problems": connecting/connection-problems.md
  - "File Transfers":
    - "Secure Copy File Transfers": "file-transfers/secure-copy-file-transfers.md"
    - "OOD File Transfers": file-transfers/ood-file-transfers.md
  - "Resource":
    - "Architecture": "resource/architecture.md"
  - "Software":
    - "AI": 
      - "Pytorch": "software/pytorch.md"
    - "Visualization":
      - "RStudio": software/rstudio.md
      - "VS Code": software/vs_code.md  
      - "Matlab": software/matlab.md
      - "jupyter": software/jupyter.md 
    - "Molecular Dynamics":
      - "Amber": software/amber.md
      - "Lammps": software/lammps.md
    - "Benchmark":
      - "OSU": software/osu.md
      - "HPL": software/hpl.md
  - "Storage":
    - "Storage Locations": storage/storage-locations.md
    - "Home Folder Quota": storage/home-quota.md
    - "Querying Quotas": storage/querying-storage.md
  - "HPC tutorial":
    - "Episode 0": hpc-tutorial/episode-0.md
    - "Episode 1": hpc-tutorial/episode-1.md
  - "Slurm":
    - slurm/overview.md
    - slurm/background.md
    - slurm/quickstart.md
    - slurm/temporary-files.md
    - slurm/cheat-sheet.md
    - slurm/job-scripts.md
    - slurm/memory-allocation.md
    - slurm/reservations.md
    - "Slurm Commands":
        - "srun": slurm/commands-srun.md
        - "sbatch": slurm/commands-sbatch.md
        - "sattach": slurm/commands-sattach.md
        - "scancel": slurm/commands-scancel.md
        - "sinfo": slurm/commands-sinfo.md
        - "squeue": slurm/commands-squeue.md
        - "scontrol": slurm/commands-scontrol.md
        - "sacct": slurm/commands-sacct.md
        - "Format Strings": slurm/format-strings.md
  - "OnDemand Portal":
    - "Overview": ondemand/overview.md
    - "Interactive Sessions": ondemand/interactive.md
  - "Best Practice":
    - "~/.bashrc Guide": best-practice/bashrc-guide.md
    - "Temporary Files": best-practice/temp-files.md
    - "Custom Environment Modules": best-practice/env-modules.md
    - "Install Software with Conda": best-practice/software-installation-with-conda.md
  - "Miscellaneous":
    - "Publication List": misc/publication-list.md
    - "External Guides": misc/external-resources.md
